# Generated by Django 4.2.30 on 2026-08-30 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('store_location', models.CharField(default='F20', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=150)),
                ('location', models.CharField(default='Dubai, UAE', max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('is_store_custodian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=200)),
                ('store_location', models.CharField(default='F20', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Issued', 'Issued'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToolTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=20)),
                ('return_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Needs Repair', 'Needs Repair')], max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_transactions', to='store_app.staff')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store_app.tool')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Receive', 'Receive (GRN)'), ('Issue', 'Issue to Project'), ('Return', 'Return to Store')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store_app.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.project')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.staff')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.supplier')),
            ],
        ),
    ]
