# Generated by Django 4.2.30 on 2026-08-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['material_code']},
        ),
        migrations.AlterModelOptions(
            name='materialtransaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['tool_no']},
        ),
        migrations.AlterModelOptions(
            name='tooltransaction',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock_alert',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_aed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='trn_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax TRN'),
        ),
        migrations.AddField(
            model_name='tool',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tooltransaction',
            name='gate_pass_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='reference_no',
            field=models.CharField(blank=True, help_text='Delivery Order (DO) / PO / Voucher No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Receive', 'Receive GRN (Inward)'), ('Issue', 'Issue to Site (Outward)'), ('Return', 'Return to Store (Restock)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active Execution'), ('Completed', 'Handed Over'), ('On Hold', 'On Hold')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('Available', 'Available (Store F20)'), ('Issued', 'Issued to Site'), ('Maintenance', 'Under Maintenance'), ('Scrapped', 'Decommissioned')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Pristine / Good'), ('Needs Repair', 'Needs Repair'), ('Damaged', 'Damaged / Write-off')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='store_app.staff'),
        ),
    ]
