# Generated by Django 4.2.30 on 2026-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
