# Generated by Django 4.2.30 on 2026-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_materialtransaction_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltransaction',
            name='issued_by',
            field=models.CharField(default='Manuja Shehan', max_length=150),
        ),
        migrations.AddField(
            model_name='tooltransaction',
            name='received_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Damaged', 'Damaged')], max_length=30, null=True),
        ),
    ]
