# Generated by Django 4.2.30 on 2026-08-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_tooltransaction_issued_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooltransaction',
            name='received_by',
        ),
        migrations.AddField(
            model_name='tooltransaction',
            name='received_by_store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active Execution'), ('Completed', 'Handed Over'), ('On Hold', 'On Hold')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='issued_by',
            field=models.CharField(default='Manuja Shehan', max_length=100),
        ),
    ]
