# Generated by Django 4.2.30 on 2026-08-31 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_remove_tooltransaction_received_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pr_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('generated_by', models.CharField(default='Store Custodian', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_items', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending Approval', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='issued_by',
            field=models.CharField(default='Store Custodian', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Target Completion Date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_alert',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='issued_by',
            field=models.CharField(default='Store Custodian', max_length=100),
        ),
    ]
