# Generated by Django 4.2.30 on 2026-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_staff_options_material_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='trn_number',
        ),
        migrations.AddField(
            model_name='tool',
            name='calibration_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Calibration Due Date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_alert',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='issued_by',
            field=models.CharField(default='UUDS-804, Manuja Shehan', max_length=150),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='received_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='generated_by',
            field=models.CharField(default='UUDS-804, Manuja Shehan', max_length=150),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='issued_by',
            field=models.CharField(default='UUDS-804, Manuja Shehan', max_length=150),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='received_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='received_by_store',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
