# Generated by Django 4.2.30 on 2026-08-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_supplier_trn_number_tool_calibration_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='items_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
