# Generated by Django 4.2.30 on 2026-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_purchaserequest_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
